{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ default (include "microservice-base.fullname" .) .Values.secretProviderClass.name }}
  labels:
    {{- include "microservice-base.labels" . | nindent 4 }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  parameters:
    {{- toYaml .Values.secretProviderClass.parameters | nindent 4 }}
  {{- if .Values.secretProviderClass.secretObjects }}
  secretObjects:
    {{- toYaml .Values.secretProviderClass.secretObjects | nindent 4 }}
  {{- end }}
{{- end }}
