{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microservice-base.serviceAccountName" . }}
  labels:
    {{- include "microservice-base.labels" . | nindent 4 }}
{{- end }}
