replicaCount: 2

externalServices:
  enabled: true
  services:
    - name: catalog-db
      externalName: retail-dev-catalog-db.cy960e2gkuba.us-east-1.rds.amazonaws.com
      ports:
        - name: mysql
          port: 3306
          protocol: TCP

configMap:
  data:
    RETAIL_CATALOG_PERSISTENCE_ENDPOINT: "catalog-db:3306"
    RETAIL_CATALOG_PERSISTENCE_PROVIDER: "mysql"
    

secretProviderClass:
  parameters:
    region: us-east-1
    objects: |
      - objectName: "/retail/dev/catalog/secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: DB_USER
            objectAlias: DB_USER
          - path: DB_PASS
            objectAlias: DB_PASS
          - path: DB_NAME
            objectAlias: DB_NAME
